[package]
name = "transmission-controller"
version = "0.2.0"
edition = "2021"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[dependencies]
argparse = "0.2.2"
chan = "0.1.23"
chan-signal = "0.3.3"
email = "0.0.21"
enum_primitive = "0.1.1"
itertools = "0.10.5"
lettre = "0.10.4"
lettre_email = "0.9.4"
libc = "0.2.141"
log = { version = "0.4.17", features = ["std"] }
mime = "0.3.17"
num = "0.4.0"
regex = "1.7.3"
reqwest = { version = "0.11.16", features = ["blocking"] }
rustc-serialize = "0.3.24"
shellexpand = "3.1.0"
time = "0.3.20"
legacy_time = { package = "time", version = "0.1.42" }
