[package]
name = "transmission-controller"
version = "0.1.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[dependencies]
argparse = "*"
chan = "*"
chan-signal = "*"
email = "*"
enum_primitive = "*"
hyper = "*"
itertools = "*"
#lettre = "> 0.5.0"
libc = "*"
log = "*"
mime = "*"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"

#[dependencies.hyper]
#version = "*"
#features = ["timeouts"]

[dependencies.lettre]
git = "https://github.com/lettre/lettre.git"
rev = "89c0be219d5e302aa58a8f97e679a957b25b7276"
