[package]
name = "transmission-controller"
version = "0.1.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[dependencies]
argparse = "*"
email = "*"
enum_primitive = "*"
hyper = "*"
itertools = "*"
lettre = "*"
libc = "*"
log = "*"
mime = "*"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"
