[package]
name = "transmission-controller"
version = "0.1.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

# FIXME: update the dependencies
[dependencies]
argparse = "*"
email = "*"
enum_primitive = "*"
hyper = "*"
itertools = "*"
# lettre 0.4.0 has a bug fixed in 9a93fee
lettre = { git = "https://github.com/lettre/lettre.git", rev = "9a93fee" }
log = "*"
mime = "*"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"
