[package]
name = "transmission-controller"
version = "0.2.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[dependencies]
argparse = "*"
chan = "*"
chan-signal = "*"
email = "*"
enum_primitive = "*"
hyper = "< 0.11"
itertools = "*"
lettre = "< 0.7"
libc = "*"
log = "0.3.7"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"
tokio-core = "*"

#[dependencies.hyper]
#version = "*"
#features = ["timeouts"]

#[dependencies.lettre]
#git = "https://github.com/lettre/lettre.git"
#rev = "89c0be219d5e302aa58a8f97e679a957b25b7276"
