[package]
name = "transmission-controller"
version = "0.1.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[dependencies]
argparse = "*"
chan = "*"
chan-signal = "*"
email = "*"
enum_primitive = "*"
itertools = "*"
lettre = "*"
libc = "*"
log = "*"
mime = "*"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"

[dependencies.hyper]
version = "*"
features = ["timeouts"]
