[package]
name = "transmission-controller"
version = "0.2.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[dependencies]
argparse = "*"
chan = "*"
chan-signal = "*"
email = "*"
enum_primitive = "*"
hyper = "< 0.11"
itertools = "*"
lettre = "*"
lettre_email = "*"
libc = "*"
log = "*"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"
tokio-core = "*"
