[package]
name = "transmission-controller"
version = "0.1.0"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[dependencies]
argparse = "*"
enum_primitive = "*"
hyper = "*"
itertools = "*"
log = "*"
mime = "*"
num = "*"
regex = "*"
rustc-serialize = "*"
time = "*"
